// clash.ts — base64 节点列表 → Clash/mihomo 客户端 YAML。
// 复用 singbox.ts 的 parseNodes() 解析层(同一份分享链接解析逻辑,不重复维护两套 parser),
// 只在这里做"sing-box 字段 → Clash 字段"的映射 + 极简 YAML 序列化。
// 支持 vmess / vless(含 reality + xtls-rprx-vision) / trojan / anytls / shadowsocks(ss)。
// deno-lint-ignore-file no-explicit-any

import { parseNodes } from "./singbox.ts";

function yamlStr(s: string): string {
  // 双引号包裹 + 转义,避免特殊字符(冒号、# 等)破坏 YAML 结构
  return `"${String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function yamlScalar(v: unknown): string {
  if (typeof v === "boolean" || typeof v === "number") return String(v);
  return yamlStr(String(v));
}

// 把一个 proxy 字段对象(可含嵌套 ws-opts/grpc-opts)序列化成 Clash proxies 列表里的一项。
function proxyToYaml(p: Record<string, any>): string {
  const lines: string[] = [];
  let first = true;
  for (const [k, v] of Object.entries(p)) {
    if (v === undefined || v === null || v === "") continue;
    const prefix = first ? "  - " : "    ";
    first = false;
    if (typeof v === "object" && !Array.isArray(v)) {
      lines.push(`${prefix}${k}:`);
      for (const [k2, v2] of Object.entries(v)) {
        if (v2 === undefined || v2 === null || v2 === "") continue;
        if (Array.isArray(v2)) {
          lines.push(`      ${k2}:`);
          for (const item of v2) lines.push(`        - ${yamlScalar(item)}`);
        } else {
          lines.push(`      ${k2}: ${yamlScalar(v2)}`);
        }
      }
    } else {
      lines.push(`${prefix}${k}: ${yamlScalar(v)}`);
    }
  }
  return lines.join("\n");
}

function toClashProxy(n: Record<string, any>): Record<string, any> | null {
  const base = { name: n.tag, server: n.server, port: n.server_port };
  const tls = n.tls || {};
  const transport = n.transport || {};

  const netOpts: Record<string, any> = {};
  if (transport.type === "ws") {
    netOpts.network = "ws";
    netOpts["ws-opts"] = {
      path: transport.path || "/",
      ...(transport.headers?.Host ? { headers: { Host: transport.headers.Host[0] } } : {}),
    };
  } else if (transport.type === "grpc") {
    netOpts.network = "grpc";
    netOpts["grpc-opts"] = { "grpc-service-name": transport.service_name || "" };
  } else if (transport.type === "http") {
    netOpts.network = "http";
  }

  switch (n.type) {
    case "vmess":
      return {
        ...base, type: "vmess", uuid: n.uuid, alterId: n.alter_id ?? 0,
        cipher: n.security || "auto",
        tls: !!tls.enabled,
        ...(tls.enabled ? { servername: tls.server_name } : {}),
        ...netOpts,
      };
    case "vless": {
      const reality = tls.reality;
      return {
        ...base, type: "vless", uuid: n.uuid,
        ...(n.flow ? { flow: n.flow } : {}),
        tls: !!tls.enabled,
        ...(tls.enabled ? {
          servername: tls.server_name,
          "client-fingerprint": tls.utls?.fingerprint || "chrome",
        } : {}),
        ...(reality?.enabled ? {
          "reality-opts": { "public-key": reality.public_key, "short-id": reality.short_id },
        } : {}),
        ...netOpts,
      };
    }
    case "trojan":
      return {
        ...base, type: "trojan", password: n.password,
        sni: tls.server_name,
        ...netOpts,
      };
    case "anytls":
      return {
        ...base, type: "anytls", password: n.password,
        sni: tls.server_name,
        "skip-cert-verify": !!tls.insecure,
        udp: true,
      };
    case "shadowsocks":
      return { ...base, type: "ss", cipher: n.method, password: n.password };
    default:
      return null;
  }
}

export function toClashYaml(input: string): string {
  const nodes = parseNodes(input);

  // name 去重(Clash 同样要求 proxy name 唯一)
  const seen = new Map<string, number>();
  for (const n of nodes) {
    if (seen.has(n.tag)) { const c = seen.get(n.tag)! + 1; seen.set(n.tag, c); n.tag = `${n.tag}-${c}`; }
    else seen.set(n.tag, 0);
  }

  const proxies = nodes.map(toClashProxy).filter((p): p is Record<string, any> => p !== null);
  const names = proxies.map((p) => p.name);

  const lines: string[] = [];
  lines.push("# generated by proxy-sub (clash)");
  lines.push("# profile-update-interval: 6");
  lines.push("mixed-port: 7890");
  lines.push("allow-lan: true");
  lines.push("mode: rule");
  lines.push("log-level: warning");
  lines.push("proxies:");
  for (const p of proxies) lines.push(proxyToYaml(p));
  lines.push("proxy-groups:");
  lines.push("  - name: PROXY");
  lines.push("    type: select");
  lines.push(`    proxies: [${["自动选择", ...names, "DIRECT"].map(yamlStr).join(", ")}]`);
  lines.push("  - name: 自动选择");
  lines.push("    type: url-test");
  lines.push(`    proxies: [${names.map(yamlStr).join(", ")}]`);
  lines.push("    url: http://www.gstatic.com/generate_204");
  lines.push("    interval: 300");
  lines.push("rules:");
  lines.push("  - MATCH,PROXY");
  return lines.join("\n") + "\n";
}
