// loon.ts — base64 节点列表 → Loon 配置([Proxy] 段)。
//
// Loon 支持 vless(含 reality)、anytls、trojan、vmess、ss,US 池里的三种协议都吃得下。
//
// 语法(名字=类型,服务器,端口,"凭据",key=value,...):
//   Name=vless,host,port,"<uuid>",transport=tcp,over-tls=true,sni=<sni>,public-key="<pbk>",short-id=<sid>,flow=xtls-rprx-vision,udp=true
//   Name=trojan,host,port,"<pw>",tls-name=<sni>,udp=true
//   Name=anytls,host,port,"<pw>",tls-name=<sni>,udp=true
// deno-lint-ignore-file no-explicit-any

import { parseNodes } from "./singbox.ts";
import { batchLabelOf, dedupeTags, isMarker, keepSupported, sanitizeInlineName } from "./fmt-util.ts";

export const LOON_PROTOCOLS = ["vless", "anytls", "trojan", "vmess", "shadowsocks"] as const;

// Loon 的 reality 用 sni + public-key + short-id 表达;非 reality 的 TLS 用 tls-name 表达。
// 两套字段不能混着写,所以这里分开处理。
function tlsTail(n: any): string[] {
  const tls = n.tls || {};
  const out: string[] = [];
  if (!tls.enabled) return out;
  if (tls.insecure) out.push("skip-cert-verify=true");
  if (tls.reality?.enabled) {
    if (tls.server_name) out.push(`sni=${tls.server_name}`);
    if (tls.reality.public_key) out.push(`public-key="${tls.reality.public_key}"`);
    if (tls.reality.short_id) out.push(`short-id=${tls.reality.short_id}`);
  } else if (tls.server_name) {
    out.push(`tls-name=${tls.server_name}`);
  }
  return out;
}

function transportTail(n: any): string[] | null {
  const t = n.transport || {};
  if (!t.type || t.type === "tcp") return ["transport=tcp"];
  if (t.type === "ws") {
    const out = ["transport=ws"];
    if (t.path) out.push(`path=${t.path}`);
    const host = t.headers?.Host?.[0];
    if (host) out.push(`host=${host}`);
    return out;
  }
  if (t.type === "http") {
    const out = ["transport=http"];
    if (t.path) out.push(`path=${t.path}`);
    if (t.host?.[0]) out.push(`host=${t.host[0]}`);
    return out;
  }
  return null; // grpc → Loon 表达不了
}

function lineFor(n: any): string | null {
  const name = sanitizeInlineName(n.tag);
  const tls = n.tls || {};

  if (n.type === "vless") {
    // Loon 的 vless 只认 xtls-rprx-vision 这一种 flow
    if (n.flow && n.flow !== "xtls-rprx-vision") return null;
    const tr = transportTail(n);
    if (!tr) return null;
    const p = [`${name}=vless,${n.server},${n.server_port},"${n.uuid}"`, ...tr];
    if (tls.enabled) p.push("over-tls=true");
    p.push(...tlsTail(n));
    if (n.flow) p.push(`flow=${n.flow}`);
    p.push("udp=true");
    return p.join(",");
  }

  if (n.type === "trojan") {
    const t = n.transport || {};
    // Loon 的 trojan 只支持裸 TCP 和 ws
    if (t.type && t.type !== "ws") return null;
    const p = [`${name}=trojan,${n.server},${n.server_port},"${n.password}"`];
    if (t.type === "ws") {
      p.push("transport=ws");
      if (t.path) p.push(`path=${t.path}`);
      const host = t.headers?.Host?.[0];
      if (host) p.push(`host=${host}`);
    }
    p.push(...tlsTail(n), "udp=true");
    return p.join(",");
  }

  if (n.type === "anytls") {
    if (n.transport?.type) return null; // Loon 的 anytls 只支持裸 TCP 承载
    const p = [`${name}=anytls,${n.server},${n.server_port},"${n.password}"`];
    p.push(...tlsTail(n), "udp=true");
    return p.join(",");
  }

  if (n.type === "vmess") {
    const tr = transportTail(n);
    if (!tr) return null;
    const p = [`${name}=vmess,${n.server},${n.server_port},auto,"${n.uuid}"`, ...tr];
    if (tls.enabled) p.push("over-tls=true");
    p.push(...tlsTail(n), "udp=true");
    return p.join(",");
  }

  if (n.type === "shadowsocks") {
    return `${name}=shadowsocks,${n.server},${n.server_port},${n.method},"${n.password}",udp=true`;
  }

  return null;
}

export function toLoonConf(input: string): string {
  const all = parseNodes(input);
  const label = batchLabelOf(all);
  const nodes = keepSupported(all.filter((n) => !isMarker(n)), LOON_PROTOCOLS);
  dedupeTags(nodes);

  const proxies: string[] = [];
  const names: string[] = [];
  for (const n of nodes) {
    const line = lineFor(n);
    if (line) {
      proxies.push(line);
      names.push(sanitizeInlineName(n.tag));
    }
  }

  const out: string[] = [];
  out.push("# generated by proxy-sub (Loon)");
  if (label) out.push(`# ${label}`);
  out.push("");
  out.push("[Proxy]");
  for (const line of proxies) out.push(line);
  out.push("");
  out.push("[Proxy Group]");
  if (names.length) {
    out.push(`PROXY = select,自动选择,${names.join(",")},DIRECT`);
    out.push(`自动选择 = url-test,${names.join(",")},url=http://www.gstatic.com/generate_204,interval=300`);
  } else {
    out.push("PROXY = select,DIRECT");
  }
  out.push("");
  out.push("[Rule]");
  out.push("GEOIP,CN,DIRECT");
  out.push("FINAL,PROXY");
  return out.join("\n") + "\n";
}
