// quanx.ts — base64 节点列表 → Quantumult X 的 server_local 行格式。
//
// QX 的订阅(server_remote)拉到的就是一行一个节点的纯文本,没有段落头,所以这里直接输出行。
// QX 支持 vless 和 anytls(跟 Surge 不一样),所以 US 池里的三种协议它都吃得下。
//
// 语法(逗号分隔的 key=value,第一段是 类型=服务器:端口):
//   vless=host:port,method=none,password=<uuid>,obfs=over-tls,tls-host=<sni>,tag=<名字>
//   trojan=host:port,password=<pw>,over-tls=true,tls-host=<sni>,tag=<名字>
//   anytls=host:port,password=<pw>,over-tls=true,tls-host=<sni>,tag=<名字>
// deno-lint-ignore-file no-explicit-any

import { parseNodes } from "./singbox.ts";
import { batchLabelOf, dedupeTags, isMarker, keepSupported, sanitizeInlineName } from "./fmt-util.ts";

export const QUANX_PROTOCOLS = ["vless", "anytls", "trojan", "vmess", "shadowsocks"] as const;

// QX 里 obfs 只认 ws / wss / over-tls / http 这几种,grpc 表达不了。
function obfsParams(n: any): string[] | null {
  const t = n.transport || {};
  const tls = n.tls || {};
  if (!t.type || t.type === "tcp") {
    return tls.enabled ? ["obfs=over-tls"] : [];
  }
  if (t.type === "ws") {
    const out = [tls.enabled ? "obfs=wss" : "obfs=ws"];
    if (t.path) out.push(`obfs-uri=${t.path}`);
    const host = t.headers?.Host?.[0];
    if (host) out.push(`obfs-host=${host}`);
    return out;
  }
  return null; // grpc / http → QX 不支持,整条节点丢弃
}

function tlsParams(n: any): string[] {
  const tls = n.tls || {};
  const out: string[] = [];
  if (!tls.enabled) return out;
  if (tls.server_name) out.push(`tls-host=${tls.server_name}`);
  out.push(`tls-verification=${tls.insecure ? "false" : "true"}`);
  // reality 在 QX 里用这两个专门的字段表达
  if (tls.reality?.enabled) {
    if (tls.reality.public_key) out.push(`reality-base64-pubkey=${tls.reality.public_key}`);
    if (tls.reality.short_id) out.push(`reality-hex-shortid=${tls.reality.short_id}`);
  }
  return out;
}

function lineFor(n: any): string | null {
  const name = sanitizeInlineName(n.tag);
  const obfs = obfsParams(n);
  if (obfs === null) return null;
  const tls = n.tls || {};

  if (n.type === "vless") {
    // QX 只支持 xtls-rprx-vision 这一种 flow,其他的直接丢弃而不是硬写进去。
    if (n.flow && n.flow !== "xtls-rprx-vision") return null;
    const p = [`vless=${n.server}:${n.server_port}`, "method=none", `password=${n.uuid}`];
    p.push(...obfs, ...tlsParams(n));
    if (n.flow) p.push(`vless-flow=${n.flow}`);
    p.push("udp-relay=true", `tag=${name}`);
    return p.join(",");
  }

  if (n.type === "trojan") {
    const p = [`trojan=${n.server}:${n.server_port}`, `password=${n.password}`];
    // ws 时用 obfs=wss 表达 TLS,非 ws 时才写 over-tls=true(两者同时写 QX 会报错)。
    if (n.transport?.type === "ws") p.push(...obfs);
    else p.push("over-tls=true");
    p.push(...tlsParams(n).filter((x) => !x.startsWith("reality")));
    p.push("udp-relay=true", `tag=${name}`);
    return p.join(",");
  }

  if (n.type === "anytls") {
    // QX 的 anytls 只支持裸 TCP 承载
    if (n.transport?.type) return null;
    const p = [`anytls=${n.server}:${n.server_port}`, `password=${n.password}`, "over-tls=true"];
    if (tls.server_name) p.push(`tls-host=${tls.server_name}`);
    p.push(`tls-verification=${tls.insecure ? "false" : "true"}`);
    p.push("udp-relay=true", `tag=${name}`);
    return p.join(",");
  }

  if (n.type === "vmess") {
    const p = [`vmess=${n.server}:${n.server_port}`, "method=chacha20-ietf-poly1305", `password=${n.uuid}`];
    p.push(...obfs, ...tlsParams(n).filter((x) => !x.startsWith("reality")));
    p.push("udp-relay=true", `tag=${name}`);
    return p.join(",");
  }

  if (n.type === "shadowsocks") {
    return [
      `shadowsocks=${n.server}:${n.server_port}`,
      `method=${n.method}`, `password=${n.password}`, "udp-relay=true", `tag=${name}`,
    ].join(",");
  }

  return null;
}

export function toQuanXConf(input: string): string {
  const all = parseNodes(input);
  const label = batchLabelOf(all);
  const nodes = keepSupported(all.filter((n) => !isMarker(n)), QUANX_PROTOCOLS);
  dedupeTags(nodes);

  const out: string[] = [];
  out.push("# generated by proxy-sub (Quantumult X)");
  if (label) out.push(`# ${label}`);
  for (const n of nodes) {
    const line = lineFor(n);
    if (line) out.push(line);
  }
  return out.join("\n") + "\n";
}
