// surge.ts — base64 节点列表 → Surge 5 配置(.conf)。
//
// 重要限制:Surge **不支持 vless,也不支持 anytls**。这不是这里偷懒没实现,是 Surge 本身
// 的代理类型里就没有这两种(Surge 5 支持 ss / trojan / vmess / http / socks5 / snell /
// tuic / hysteria2 / ssh)。所以 US 节点池里 vless 和 anytls 的那部分,在 Surge 这条链接上
// 会被整体摘掉,只剩 trojan(以及万一将来池子里出现的 vmess/ss)。
// 后台链接列表里会按这个规则显示"这条链接实际有几个节点",不会让人以为 100 个全都在。
//
// 语法参照 Surge 官方 proxy 段格式:
//   名字 = 类型, 服务器, 端口, 参数=值, ...
// deno-lint-ignore-file no-explicit-any

import { parseNodes } from "./singbox.ts";
import { batchLabelOf, dedupeTags, isMarker, keepSupported, sanitizeInlineName } from "./fmt-util.ts";

export const SURGE_PROTOCOLS = ["trojan", "vmess", "shadowsocks"] as const;

// Surge 的值里如果含空格/特殊字符要加引号。
function sq(v: string): string {
  return `"${String(v).replace(/"/g, "")}"`;
}

function transportParams(n: any): string[] {
  const t = n.transport || {};
  if (t.type !== "ws") return []; // Surge 只支持 ws,grpc/http 表达不了
  const out = [`ws=true`, `ws-path=${t.path || "/"}`];
  const host = t.headers?.Host?.[0];
  if (host) out.push(`ws-headers=${sq(`Host:${host}`)}`);
  return out;
}

function lineFor(n: any): string | null {
  const name = sanitizeInlineName(n.tag);
  const tls = n.tls || {};

  if (n.type === "trojan") {
    const p = [`${name} = trojan`, n.server, String(n.server_port), `password=${sq(n.password)}`];
    p.push(...transportParams(n));
    // trojan 本身就是跑在 TLS 上的,Surge 不需要再写 tls=true,但 sni 要给。
    if (tls.server_name) p.push(`sni=${sq(tls.server_name)}`);
    if (tls.insecure) p.push(`skip-cert-verify=true`);
    p.push("udp-relay=true");
    return p.join(", ");
  }

  if (n.type === "vmess") {
    const p = [`${name} = vmess`, n.server, String(n.server_port), `username=${n.uuid}`];
    p.push(...transportParams(n));
    if (tls.enabled) {
      p.push("tls=true");
      if (tls.server_name) p.push(`sni=${sq(tls.server_name)}`);
      if (tls.insecure) p.push(`skip-cert-verify=true`);
    }
    p.push("vmess-aead=true", "udp-relay=true");
    return p.join(", ");
  }

  if (n.type === "shadowsocks") {
    return [
      `${name} = ss`, n.server, String(n.server_port),
      `encrypt-method=${n.method}`, `password=${sq(n.password)}`, "udp-relay=true",
    ].join(", ");
  }

  return null; // vless / anytls / 其他 → Surge 表达不了
}

export function toSurgeConf(input: string): string {
  const all = parseNodes(input);
  const label = batchLabelOf(all);
  const nodes = keepSupported(all.filter((n) => !isMarker(n)), SURGE_PROTOCOLS);
  dedupeTags(nodes);

  const proxies: string[] = [];
  const names: string[] = [];
  for (const n of nodes) {
    const line = lineFor(n);
    if (line) {
      proxies.push(line);
      names.push(sanitizeInlineName(n.tag));
    }
  }

  const out: string[] = [];
  out.push("#!MANAGED-CONFIG interval=3600 strict=false");
  out.push("# generated by proxy-sub (Surge 5)");
  // 时间戳假节点在 Surge 里表达不了(它是个 vless),改成写在文件头的注释里,信息不丢。
  if (label) out.push(`# ${label}`);
  out.push("# 注意: Surge 不支持 vless / anytls,这两类节点已被过滤掉。");
  out.push("");
  out.push("[General]");
  out.push("loglevel = notify");
  out.push("skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local");
  out.push("dns-server = 223.5.5.5, 119.29.29.29");
  out.push("");
  out.push("[Proxy]");
  out.push("DIRECT = direct");
  for (const line of proxies) out.push(line);
  out.push("");
  out.push("[Proxy Group]");
  if (names.length) {
    out.push(`PROXY = select, 自动选择, ${names.join(", ")}, DIRECT`);
    out.push(`自动选择 = url-test, ${names.join(", ")}, url = http://www.gstatic.com/generate_204, interval = 300, tolerance = 50`);
  } else {
    // 一个节点都没有时也要给出结构合法的配置,否则 Surge 直接打不开这份 profile。
    out.push("PROXY = select, DIRECT");
  }
  out.push("");
  out.push("[Rule]");
  out.push("GEOIP,CN,DIRECT");
  out.push("FINAL,PROXY");
  return out.join("\n") + "\n";
}
